	source 'https://rubygems.org'


gem 'rails', '4.2.2'

gem 'rails-api'

#, :group => :development

#gem 'em-websocket', '~> 0.5.1'

#gem 'sqlite3'

gem 'active_model_serializers'

gem 'bcrypt', '3.1.7'

gem 'thin'

gem 'faye-websocket'

group :development, :test do

	gem 'sqlite3'

	gem 'spring'
end

group :production do
	gem 'pg'
	gem 'rails_12factor'
end
# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
